### ISSUE TITLE
"Color @usernames" doesn't work

### ISSUE THREAD

**Issue by Naeramarth** [SevenTV/chatterino7#28] opened 2021-07-11 14:46 UTC
The option "Color @usernames" doesn't seem to work. "@username" in chat messages stays white. This options works in the main chatterino fork.

Version: Windows 10, 7.3.3

**Comment by talneoran** [comment] 2021-07-11 16:41
Duplicate of upstream https://github.com/Chatterino/chatterino2/issues/2822 and also of a couple previously closed issues on this fork.
This is a known issue and is not specific to the 7TV fork, it's very inconsistent and may or may not work every time.

**Comment by zneix** [comment] 2021-07-11 16:49
Duplicates on this repository:
#23 
#8 
#5 

Duplicates on upstream Chatterino repository:
Chatterino/chatterino2#2873 
Chatterino/chatterino2#2822

Pretty please - search for existing issues prior to opening one, thanks!

**Closed by zneix** 2021-07-11 16:49 UTC
