### ISSUE TITLE
White Border on neighbouring monitors

### ISSUE THREAD

**Issue by Cheezeburgerstick** [SevenTV/chatterino7#12] opened 2021-06-08 07:31 UTC
Maximizing Chatterino causes white borders to appear on neighbouring monitors.

![image](https://user-images.githubusercontent.com/13181977/121142454-56f17a80-c87f-11eb-8851-8d3a3c9286ef.png)

Using Chatterino 7.3.2 on Windows 10.

**Comment by zneix** [comment] 2021-06-11 20:45
Duplicate of Chatterino/chatterino2#2205

**Closed** 2021-06-11 20:45 UTC
