### ISSUE TITLE
Username colors in chat

### ISSUE THREAD

**Issue by StephanBruh** [SevenTV/chatterino7#8] opened 2021-05-28 08:39 UTC
**Describe your issue**
Username colors in chat aren't working, but when you build it in debug colors do work again, when you switch to release or profile. Colors are broken again. Isn't a chatterino issue because colors work for me on chatterino 2.3.2

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 7.3.2

**Comment by zneix** [comment] 2021-05-28 10:21
Duplicate of #5, please search existing issues prior to creating a new issue.

**Closed** 2021-05-28 10:21 UTC
