### ISSUE TITLE
[7.3.5] [MacOS] Enter doesn't send message but goes to new line

### ISSUE THREAD

**Issue by haruiswaifu** [SevenTV/chatterino7#90] opened 2022-05-21 18:50 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Since the switch to 7.3.5 or any nightly version, when I press enter in the chat box, it goes to a new line instead of sending the message. I'm not pressing ctrl + enter.

I'm running on MacOS, Apple Silicon (ARM) which might be related.

### OS and Chatterino Version

Chatterino 7.3.5 (commit a0e87b960c43f8deb08bd728d18609014c1cec83), MacOS, Apple Silicon (ARM)

**Comment by jshuam** [comment] 2022-05-22 02:45
This is also happening to me on Windows 10 since downloading the most recent stable build.
It seems to be triggered by alt tabbing into Chatterino. 
However, if I alt tab in (and the issue occurs) and then click on Chatterino with my mouse, it no longer occurs.

https://user-images.githubusercontent.com/38599506/169675956-127d24da-9e07-4e59-908a-335568d24cb1.mp4

I've attached a clip of me reproducing it.
It starts with me tabbed out, then I tab in and the issue occurs, then upon clicking the issue stops.

**Comment by Felanbird** [comment] 2022-05-22 02:50
This issue happens due to changes made in chatterino/chatterino2#2340, enter no longer takes priority over all other hotkeys, so the focusing issue from chatterino/chatterino2#2844 is much more prevalent, compared to basically never being seen.

> and then click on Chatterino with my mouse, it no longer occurs.

Manual resolving of this issue comes from clicking on Chatterino as mentioned above, also removing `shift+enter` functionality is being discussed in chatterino/chatterino2#3619

**Closed as completed by Felanbird** 2022-05-22 02:50 UTC
