### ISSUE TITLE
Subscriber Emotes Menu not working correctly.

### ISSUE THREAD

**Issue by Dangerousbros** [SevenTV/chatterino7#29] opened 2021-07-11 23:18 UTC
Hello, here are some issues i've been happening since animated emotes were added.

Major Issues:
  - A row of emotes in the menu are duplicated sometimes up to 3 times.
  - Several emotes are missing either rows of emotes or individuals from a set.
  - New emotes are not added even after refreshing and several days.
   
 Minor Issues:
  - Refreshing emotes (F5) makes all/most sub emotes dissapear.
  - Follower twitch emotes do not display.

**Screenshots**

Major Issues:
Multiple rows:
https://i.imgur.com/Z8YXniY.png
https://i.imgur.com/6qD5wV8.png

Emotes missing:
https://i.imgur.com/CJRQ5RX.png
https://i.imgur.com/lK1D2NJ.png

Minor Issues:
Refreshing removing emotes:
(captured immediately after f5)
https://i.imgur.com/kgOHy7h.png

Follow emotes not displaying
https://i.imgur.com/wiMXnbM.png

**OS and Chatterino Version**

        Windows 10, Chatterino Nightly 7.3.3 (newest build)

Thanks hopes this helps!

**Comment by zneix** [comment] 2021-07-13 10:17
Duplicate of upstream issue, see pinned issue in https://github.com/chatterino/chatterino2/issues

**Closed by zneix** 2021-07-13 10:17 UTC
