### ISSUE TITLE
Colored Usernames not colored

### ISSUE THREAD

**Issue by basedbidoof** [SevenTV/chatterino7#23] opened 2021-06-26 02:43 UTC
Hi, was just chatting with someone, they also said they were facing this issue, so I figured I'd bug report.

   It seems like the Colorized Usernames feature is no longer working. They just appear white. I noticed it in the main and nightly builds. I checked my settings to verify they were proper, and yeah. I tried disabling the settings, re-enabling them, still bugged. 
  I thought I saw them work the other night, but I honestly I think I was using the wrong version on accident when I first booted..

**Screenshots**

https://i.imgur.com/dkgSiQc.png
 https://i.imgur.com/LZdQcHF.png 
 https://i.imgur.com/EV7IH1c.png 

**OS and Chatterino Version**

        Windows 10, Chatterino 7.3.2   
    & 
        Windows 10, Chatterino Nightly 7.3.2

**Comment by zneix** [comment] 2021-06-26 02:49
Duplicate of god knows how many issues. Prior to opening a new issue search for existing ones to avoid opening duplicates, it's not that hard.

Duplicates on this repository:
![forsenY](https://cdn.zneix.eu/IOgtP9Z.png)

Duplicates on upstream Chatterino repository:
Chatterino/chatterino2#2873 
Chatterino/chatterino2#2822

**Closed by zneix** 2021-06-26 02:49 UTC

**Comment by StephanBruh** [comment] 2021-06-26 10:11
Download chatterino7 portable version, works in there. Little workaround for now
