### ISSUE TITLE
7TV and FFZ emotes scale differently when zooming in

### ISSUE THREAD

**Issue by Velegand** [SevenTV/chatterino7#71] opened 2022-03-10 22:53 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

This has always been an issue in chatterino 7 but I never reported it.
I made two 128x128 black square emotes to test this out
https://7tv.app/emotes/60fafe4e0ba9b4d774fb9cd6 and https://www.frankerfacez.com/emoticon/675476-blackSquare
When you zoom in at a certain point the 7tv emotes get smaller than other emotes but even if you just barely zoom in 7tv emotes get a bit smaller.
FFZ and BTTV emotes behave the same.

### Screenshots

https://user-images.githubusercontent.com/69394829/157765862-d3a28758-c285-4f30-9a93-2e730e9d0cd3.mp4

### OS and Chatterino Version

Chatterino Nightly 7.3.4 (commit a86079d88, built on ) on Windows 10

**Comment by AnatoleAM** [comment] 2022-03-10 22:59
This is caused by incorrect `2x` and `3x` image scales in the 7TV CDN, which are not actually 2x or 3x. Therefore in certain settings where those scales are used, they will look out of place next to that of other providers. This will be fixed after the CDN undergoes a reprocessing job, which is scheduled to occur close to the deployment of API v3 into production.

**Closed by AnatoleAM** 2022-03-10 22:59 UTC
