### ISSUE TITLE
highlights function data gone after new login

### ISSUE THREAD

**Issue by jann-amh** [SevenTV/chatterino7#14] opened 2021-06-14 21:24 UTC
After i added my accout back due new login, all of the data from the highlights function is gone. 
(OS --> Win 10 64bit)
(Version 7.3.2)

**Comment by zneix** [comment] 2021-06-14 21:41
Duplicate of #2425
See https://github.com/Chatterino/chatterino2/issues/2425#issuecomment-833909049

**Closed by zneix** 2021-06-14 21:41 UTC
